### ISSUE TITLE
Cannot connect to postgresql 13+

### ISSUE THREAD

**Issue by ali-1989** [tomyeh/postgresql#22]
Hi,

not connected by [scram-sha-256]

**Comment by marcotas** [comment]
Hey @tomyeh any updates on this one? Working with this package is much better than `postgres` package. I'm building a backend framework based on your package. I already have 457+ tests with it but I was running with postgres 11. When I decided to upgrade to postgres:latest in my docker it just doesn't work. Is there anything I can do to help with it? I'm still reading your code though but definitely you would be much faster to make this upgrade (I assume). Thank you so much for this package! I didn't want to move to another package `postgres` though. Do you think you will be able to make this update soon?

**Comment by tomyeh** [comment]
Sorry, not working on it. Welcome your contributions:)

**Comment by ali-1989** [comment]
I resolved this.

first: must change password encryption in [/etc/postgresql/--version--/main/postgresql.conf]
- sudo nano /etc/postgresql/15/main/postgresql.conf

change [#password_encryption = scram-sha-256]  to  [password_encryption = md5]
save and close

second: must change password method in [/etc/postgresql/--version--/main/pg_hba.conf]
- sudo nano /etc/postgresql/15/main/pg_hba.conf

change any scram-sha-256 to md5
save and close

restart postgres:
    - sudo service postgresql reload
    - sudo service postgresql restar
	

note: this opration not work for old user. and you must reset you password.

you can see result by (select * FROM pg_authid WHERE rolcanlogin;)  and you must see md5... in rolpassword column.
