### ISSUE TITLE
About return function

### ISSUE THREAD

**Issue by gustavozm** [tomyeh/postgresql#6]
Hello, sorry for my question.

I'm trying to get the return of the function below, which should return a List with the result of the select and return is null.

Can you help me please.

See function:

queryExec(String tipo, String sql, List param, List valparam) async {
  List wret;
  connect(uri).then((conn) {
    switch (tipo.toUpperCase()) {
      case 'SELECT':
        {
          conn
              .query(sql, {param: valparam})
              .toList()
              .then((result) {
                wret = result;
                return wret;
              })
              .then((_) => conn.close())
              .catchError((err) => print('Query ERRO: $err'));
          break;
        }
    }
  });
//  return wret;
}

**Comment by tomyeh** [comment]
Please ask question on stackoverflow or Dart's discussion group.

Here is for reporting bugs or asking features.
